### ISSUE TITLE
How to keep a certain boundary not disappear? 

### ISSUE THREAD

**Issue by xhzengAIB** [Vinodh-G/ParallaxTableViewHeader#1]
Hi! @Vinodh-G 

Like the picture:

![2cb1b32f-bc40-42b1-93c5-d35df329ef33](https://cloud.githubusercontent.com/assets/1969908/5295609/3f0d4cf8-7bd5-11e4-820f-bd472aae9c68.png)

keep the header certain boundary not disappear, aways show in TableView.

Jack

**Comment by Urkman** [comment]
Any Updates on this?

**Comment by Vinodh-G** [comment]
Not working on it now
