### ISSUE TITLE
How to add to it an array of images which can scroll horizontally ? 

### ISSUE THREAD

**Issue by leewi9** [Vinodh-G/ParallaxTableViewHeader#17]

**Comment by Vinodh-G** [comment]
Use API `parallaxHeaderViewWithSubView:` pass a horizontal UIScrollView or a UICollectionView as subview parameter.

Load the UIcollectionView or UIScrollView with array of Images which can be scrolled.

**Comment by leewi9** [comment]
Thanks. I tried, but I found another problem, when I scroll the images, it seems the first image is always at the background, beneath the current presenting image. pls see this gif for detail.

![untitled](https://cloud.githubusercontent.com/assets/10832544/14407845/bbd729c0-ff0a-11e5-8c69-4753844b219d.gif)

my code is like this, if you need full code, i can give you the whole project.
![snip20160410_2](https://cloud.githubusercontent.com/assets/10832544/14407852/0edc3e80-ff0b-11e5-9306-c0307ddc4fd7.png)

besides, i'm not sure wether this is caused by your `ParallaxTableViewHeader` or other framework, i use `SDCycleScrollView` also in the project.

regards,
