### ISSUE TITLE
ParallaxHeaderView - Image View from server (URL)?

### ISSUE THREAD

**Issue by MrRochito** [Vinodh-G/ParallaxTableViewHeader#8]
Hi, can i put the header view from URL?

Regards.

**Comment by Vinodh-G** [comment]
Hello Hacoga,

Right now it is not supported, I am working round it, If you need it now, implement using API parallaxHeaderViewWithSubView: and pass the UIImageView as subview.

Include Extensions files listed below
https://github.com/Vinodh-G/UIImageView-Async-download/blob/master/TopApps/UIImageView%2BNetworking.h
https://github.com/Vinodh-G/UIImageView-Async-download/blob/master/TopApps/UIImageView%2BNetworking.m

Later for that UIImageView  call
__weak ViewController *weakSelf = self;
[imageView setImageURL:url withCompletionBlock:^(BOOL succes, UIImage *image, NSError *error){
            if (succes)
            {
                weakSelf.imageView = image;
            }
];

Thanks,
Vinodh

**Comment by MrRochito** [comment]
Thanks! a lot! Yea.
I used a similar - SDWebImage.

 SDWebImageManager *manager = [SDWebImageManager sharedManager];

```
[manager downloadImageWithURL:urlImagen options:0 progress:^(NSInteger receivedSize, NSInteger expectedSize) {

} completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
    if (image)
    {
        ParallaxHeaderView *headerView = [ParallaxHeaderView parallaxHeaderViewWithImage:image forSize:CGSizeMake(self.iboTableView.frame.size.width, 300)];

        headerView.headerTitleLabel.text = self.item.title;
        [self.iboTableView setTableHeaderView:headerView];

        valueTable = 1;
        [self.iboTableView reloadData];
    }else{


    }
}];
```
