### ISSUE TITLE
Page Control

### ISSUE THREAD

**Issue by arasu01** [Vinodh-G/ParallaxTableViewHeader#9]
Is there is any way to include the page control to the parallax effect.

**Comment by Vinodh-G** [comment]
Yes, you can,
use parallaxHeaderViewWithSubView: api with custom subview containing UIPageControl or   UIScrollView or any UIView and handle respective events in controller class which uses ParallaxTableViewHeader view.

Let me know if anything else needed.

Thanks,
Vinodh
